name: Daily Paris Arrondissement Scraper

on:
  schedule:
    - cron: '0 6 * * *'  # Tous les jours à 6h00
  workflow_dispatch:  # Permet de lancer manuellement

env:
  PROJECT_ID: oversight-datalake

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: |
        cd simple-scraper
        npm install

    - name: Setup BigQuery credentials and run scraper
      run: |
        cd simple-scraper
        echo '${{ secrets.GCP_SA_KEY }}' > bigquery-credentials.json
        node scraper.js
